<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <LangVersion>9.0</LangVersion>
    <Nullable>disable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <ImplicitUsings>disable</ImplicitUsings>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <AssemblyName>ServerRates</AssemblyName>
    <RootNamespace>ServerRates</RootNamespace>
    <Product>ServerRates</Product>
    <Version>1.4.9</Version>
    <ModVersion>1.4.9</ModVersion>
    <OutputPath>bin\$(Configuration)\</OutputPath>
    <DebugType>portable</DebugType>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="BepInEx">
      <HintPath>$(BepInExDir)\core\BepInEx.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="0Harmony">
      <HintPath>$(BepInExDir)\core\0Harmony.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="assembly_valheim">
      <HintPath>$(ManagedDir)\assembly_valheim.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="assembly_utils">
      <HintPath>$(ManagedDir)\assembly_utils.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>$(ManagedDir)\UnityEngine.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>$(ManagedDir)\UnityEngine.CoreModule.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.PhysicsModule">
      <HintPath>$(ManagedDir)\UnityEngine.PhysicsModule.dll</HintPath>
      <Private>False</Private>
    </Reference>
  </ItemGroup>

  <Target Name="Deploy" AfterTargets="Build">
    <PropertyGroup>
      <DeployDir>$(BepInExDir)\plugins\ServerRates</DeployDir>
      <ThunderstorePackRoot>$(MSBuildThisFileDirectory)thunderstore\ServerRates</ThunderstorePackRoot>
    </PropertyGroup>
    <MakeDir Directories="$(DeployDir)" />
    <Copy SourceFiles="$(TargetPath)" DestinationFolder="$(DeployDir)" OverwriteReadOnlyFiles="true" />
    <MakeDir Directories="$(ThunderstorePackRoot)\plugins\ServerRates" />
    <Copy SourceFiles="$(TargetPath)" DestinationFolder="$(ThunderstorePackRoot)\plugins\ServerRates" OverwriteReadOnlyFiles="true" />
  </Target>
</Project>
